title: Ishwar Netaam
description: A passionate software developer specializing in web development.
url: "https://ishwarnetam.github.io" # your site URL
baseurl: "" # leave empty for user site

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author
author:
  name: Laxmi Prasoon Barik
  email: your-email@example.com

# Social Links
social:
  github: "https://github.com/LAXMIPRASOON"
  twitter: "https://twitter.com/yourusername"
  linkedin: "https://linkedin.com/in/yourusername"

# Navigation
navigation:
  - title: Home
    url: "/"
  - title: About Me
    url: "/aboutme.html"
  - title: Research
    url: "/research.html"
  - title: Contact
    url: "/contact.html"

# SEO Configuration
seo:
  title: "Ishwar Netaam Portfolio"
  description: "A passionate software developer specializing in web development."
  keywords: ["developer", "software", "web development", "portfolio"]
  lang: "en"
  twitter:
    site: "@yourtwitterhandle"
    creator: "@yourtwitterhandle"
  open_graph:
    type: "website"
    locale: "en_US"
    url: "https://github.com/LAXMIPRASOON/laxmiprasoonbarik.github.io"
    title: "Laxmi Prasoon Portfolio"
    description: "A passionate software developer specializing in web development."
    image: "/assets/images/seo-image.jpg"

# Google Analytics (Optional)
google_analytics: "UA-XXXXXXXXX-X"
