- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.GH_PAT }}  # Use PAT instead of GITHUB_TOKEN
    publish_dir: ./_site
    publish_branch: gh-pages  # Make sure this is the correct branch
